image: node:14.16.1

before_script:
  - node -v

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
    - printenv NPM_TOKEN
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm i @falconstudios/ns-player
  artifacts:
    paths:
      - public
  only:
    - master